[project]
name = "AI-Tutor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.1.1",
    "boto3>=1.34.129",
    "cryptography>=42.0.8",
    "email-validator>=2.2.0",
    "fastapi==0.110.1",
    "flake8>=7.0.0",
    "isort>=5.13.2",
    "motor==3.3.1",
    "mypy>=1.8.0",
    "passlib>=1.7.4",
    "pydantic>=2.6.4",
    "pyjwt>=2.10.1",
    "pymongo==4.5.0",
    "pytest>=8.0.0",
    "python-dotenv>=1.0.1",
    "python-jose>=3.3.0",
    "requests-oauthlib>=2.0.0",
    "requests>=2.31.0",
    "tzdata>=2024.2",
    "uvicorn==0.25.0",
    "pandas>=2.2.0",
    "numpy>=1.26.0",
    "python-multipart>=0.0.9",
    "jq>=1.6.0",
    "typer>=0.9.0",
    "google-generativeai>=0.3.1",
    "opencv-python>=4.7.0.72",
    "pillow>=9.4.0",
    "mss>=9.0.1",
]
